-- Pharmacy chain schema (PostgreSQL 13+)
--
-- Tables follow the ER design in docs/report_final.pdf. Compared with the
-- original course submission:
--   * surrogate keys are identity columns, so the app can insert rows
--     without choosing IDs (the old INT NOT NULL keys made every insert
--     from the app fail)
--   * dates are DATE, money is NUMERIC, and CHECK constraints reject bad data
--   * bill has foreign keys to patient, doctor and medicine, plus a timestamp
--   * employee.db_role links a PostgreSQL login to the store it works in

BEGIN;

DROP TABLE IF EXISTS bill, contains, associated_with, patient, employee,
                     medicine, doctor, pharmacy CASCADE;

CREATE TABLE pharmacy (
    store_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name  VARCHAR(40) NOT NULL,
    address     VARCHAR(60) NOT NULL,
    city        VARCHAR(30) NOT NULL,
    state       VARCHAR(30) NOT NULL,
    pincode     CHAR(6)     NOT NULL CHECK (pincode ~ '^[0-9]{6}$')
);

CREATE TABLE doctor (
    doc_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name    VARCHAR(40) NOT NULL,
    address     VARCHAR(60),
    contact     CHAR(10)    NOT NULL CHECK (contact ~ '^[0-9]{10}$'),
    hospital    VARCHAR(40)
);

CREATE TABLE employee (
    eid         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_name    VARCHAR(40) NOT NULL,
    address     VARCHAR(60) NOT NULL,
    sex         VARCHAR(6)  NOT NULL CHECK (sex IN ('Male', 'Female', 'Other')),
    salary      NUMERIC(10, 2) NOT NULL CHECK (salary > 0),
    contact     CHAR(10)    NOT NULL CHECK (contact ~ '^[0-9]{10}$'),
    store_id    INT NOT NULL REFERENCES pharmacy ON UPDATE CASCADE,
    db_role     NAME UNIQUE          -- PostgreSQL login used by this employee
);

CREATE TABLE medicine (
    drug_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_name    VARCHAR(40) NOT NULL UNIQUE,
    mfg_date     DATE NOT NULL,
    exp_date     DATE NOT NULL,
    price        NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    manufacturer VARCHAR(40) NOT NULL,
    CHECK (exp_date > mfg_date)
);

CREATE TABLE patient (
    pid         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_name      VARCHAR(40) NOT NULL,
    address     VARCHAR(60) NOT NULL,
    sex         VARCHAR(6)  NOT NULL CHECK (sex IN ('Male', 'Female', 'Other')),
    contact     CHAR(10)    NOT NULL CHECK (contact ~ '^[0-9]{10}$'),
    doc_id      INT NOT NULL REFERENCES doctor,
    store_id    INT REFERENCES pharmacy
);

-- stock of each medicine in each store
CREATE TABLE contains (
    drug_id     INT NOT NULL REFERENCES medicine ON DELETE CASCADE,
    store_id    INT NOT NULL REFERENCES pharmacy ON DELETE CASCADE,
    quantity    INT NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    PRIMARY KEY (drug_id, store_id)
);

-- doctors whose prescriptions a store accepts
CREATE TABLE associated_with (
    doc_id      INT NOT NULL REFERENCES doctor ON DELETE CASCADE,
    store_id    INT NOT NULL REFERENCES pharmacy ON DELETE CASCADE,
    PRIMARY KEY (doc_id, store_id)
);

CREATE TABLE bill (
    bill_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid         INT NOT NULL REFERENCES patient,
    doc_id      INT NOT NULL REFERENCES doctor,
    drug_id     INT NOT NULL REFERENCES medicine,
    quantity    INT NOT NULL CHECK (quantity > 0),
    amount      NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    store_id    INT NOT NULL REFERENCES pharmacy,
    eid         INT REFERENCES employee,
    billed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- foreign keys used in searches and joins
CREATE INDEX ON employee (store_id);
CREATE INDEX ON patient (doc_id);
CREATE INDEX ON patient (store_id);
CREATE INDEX ON contains (store_id);
CREATE INDEX ON bill (pid);
CREATE INDEX ON bill (store_id, billed_at);
CREATE INDEX ON medicine (lower(drug_name));

COMMIT;
